modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="le_vrai_mod"
version="1.0.0"
displayName="Le vrai mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="emman, MCreator"

[[dependencies.le_vrai_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




